export const POSTS_FETCHING = 'POSTS_FETCHING';
export const POSTS_FETCHED = 'POSTS_FETCHED';
export const POSTS_FETCH_ERROR = 'POSTS_FETCH_ERROR';
export const POST_SUBMITTED = 'POST_SUBMITTED';
export const POST_SAVED = 'POST_SAVED';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_UPDATING = 'POST_UPDATING';
export const POST_SAVE_ERROR = 'POST_SAVE_ERROR';
export const POST_DELETING = 'POST_DELETING';
export const POST_DELETE_ERROR = 'POST_DELETE_ERROR';
export const POST_DELETED = 'POST_DELETED';
export const HAMBURGER_MENU_CLICKED = 'HAMBURGER_MENU_CLICKED';
export const BODY_CLICKED = 'BODY_CLICKED';

// Router
export const ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
